### ISSUE TITLE
is this a gpl version

### ISSUE THREAD

**Issue by jjab2020** [syscobra/extjs-admin-dashboard-template#1]
Hi,

I would like thank you about this useful work.

I have a few questions:
1) is this a gpl version?
2)how can i change the navigation ui color from black to another color on the left of template?

Any help any documentations to play with style of navigation tree  ui mixin.

Have a nice day.

**Comment by syscobra** [comment]
Hello,
Thank you.

1. The license is the same as the GPL version of ExtJS, and it's added to the source: 
https://github.com/syscobra/extjs-admin-dashboard-template/blob/master/LICENSE
2. There is various ways of doing that:
- One version is(if you are not good at sass or just want to change that color and thats all):
`.x-treelist-navigation {background-color:#the_color_you_want}`
you can add it to sass/src/view/main/Main.scss
- Another version (the good way) is to ask yourself for which theme you want to change it, modern, classic or both:
- To change the color you have to add this variable to the sass var files:

> $panel-navigation-background-color: #the_color_you_want;
- To change in Classic Theme, you have to put that in:
`classic/sass/var/view/main/Main.scss`
- In Modern Theme:
`modern/sass/var/view/main/Main.scss`
- Both themes at once:
`sass/var/view/main/Main.scss`

**Comment by jjab2020** [comment]
Thank you very much friend , i have seen someone who create a new package with new modification is this the good why i'm new in using sass.

Have a nice day friend :)
